export const SIGN_UP_REQUEST_PROCESSING = "SIGN_UP_REQUEST_PROCESSING";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";
export const SIGN_UP_REQUEST_FAILED = "SIGN_UP_REQUEST_FAILED";

export const SIGN_IN_REQUEST_PROCESSING = "SIGN_IN_REQUEST_PROCESSING";
export const SIGN_IN_REQUEST_SUCCESS = "SIGN_IN_REQUEST_SUCCESS";
export const SIGN_IN_REQUEST_FAILED = "SIGN_IN_REQUEST_FAILED";

export const UPDATE_USER_DATA_REQUEST_PROCESSING = "UPDATE_USER_DATA_REQUEST_PROCESSING";
export const UPDATE_USER_DATA_REQUEST_SUCCESS = "UPDATE_USER_DATA_REQUEST_SUCCESS";
export const UPDATE_USER_DATA_REQUEST_FAILED = "UPDATE_USER_DATA_REQUEST_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const SET_EMAIL = "SET_EMAIL";
export const SET_VERIFICATION_CODE = "SET_VERIFICATION_CODE";
export const SET_IS_EMAIL_MODAL_OPENED = "SET_IS_EMAIL_MODAL_OPENED";
export const SET_IS_USERNAME_MODAL_OPENED = "SET_IS_USERNAME_MODAL_OPENED";
export const SET_IS_CODE_SENT = "SET_IS_CODE_SENT";
export const SET_LOADING = "SET_LOADING";

export const UPDATE_AVATAR_DETAILS = "UPDATE_AVATAR_DETAILS";
